id: P001737
initial_creation_type: ocr
created_at: 26/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W2DB4599
  title: 'སི་ཁྲོན་བོད་རིག་པའི་ཞིབ་འཇུག ༼༦༽ '
  author: ''
  volumes:
    280450613c764af9b58bd619613c0436:
      image_group_id: I1PD28125
      title: ''
      volume_number: 1
      total_pages: 470
      base_file: v001.txt
